# Custom Language File for Launcher Customizer

[ejs.app]
title = "PumpCan studios"

[ejs.landing]
mediaGitHubURL = "https://github.com/chinelodedo/PumpCan_studios"
mediaTwitterURL = "https://x.com/interloperSMP"
mediaInstagramURL = "https://www.instagram.com/_quaseperfeito/"
mediaYouTubeURL = "https://www.youtube.com/@interloperSMP"
mediaDiscordURL = "https://discord.gg/XzU9ea6jSB"

[ejs.settings]
sourceGithubLink = "https://github.com/chinelodedo/PumpCan_studios"
supportLink = "https://github.com/chinelodedo/PumpCan_studios/issues"

[ejs.welcome]
welcomeHeader = "Bem vindo(a) ao launcher da PumpCan_studios!"
welcomeDescription = "A PumpCan studios é uma empresa destinada à criação e desenvolvimento de assets para jogos, responsável por arquiteturas e por modelagem, matrizes artísticas e gráficas. (projeto destinado a Interloper_SMP)"
welcomeDescCTA = "Apenas clique para prosseguir"
